artifact_location: file:///C:/Users/iamsh/OneDrive/Desktop/AI Project/fintel/mlflow_runs/153180820146054763
creation_time: 1772834566372
experiment_id: '153180820146054763'
last_update_time: 1772834566372
lifecycle_stage: active
name: FinTel_PerRegime_v1
workspace: default
