artifact_uri: file:///C:/Users/iamsh/OneDrive/Desktop/AI Project/fintel/mlflow_runs/153180820146054763/fd476c2d5c34499fac150cf0e822725f/artifacts
end_time: 1772835406104
entry_point_name: ''
experiment_id: '153180820146054763'
lifecycle_stage: active
run_id: fd476c2d5c34499fac150cf0e822725f
run_name: pre_gfc_peak
source_name: ''
source_type: 4
source_version: ''
start_time: 1772835404350
status: 3
tags: []
user_id: iamsh
