artifact_uri: file:///C:/Users/iamsh/OneDrive/Desktop/AI Project/fintel/mlflow_runs/153180820146054763/6cf7d9531b734fe7bc5401c5705e810a/artifacts
end_time: 1772834567863
entry_point_name: ''
experiment_id: '153180820146054763'
lifecycle_stage: active
run_id: 6cf7d9531b734fe7bc5401c5705e810a
run_name: ai_era_acceleration
source_name: ''
source_type: 4
source_version: ''
start_time: 1772834566923
status: 4
tags: []
user_id: iamsh
