artifact_uri: file:///C:/Users/iamsh/OneDrive/Desktop/AI Project/fintel/mlflow_runs/153180820146054763/df0dd5612ef04ba6ab17e28d6162a2fd/artifacts
end_time: 1772835410876
entry_point_name: ''
experiment_id: '153180820146054763'
lifecycle_stage: active
run_id: df0dd5612ef04ba6ab17e28d6162a2fd
run_name: rate_hike_shock
source_name: ''
source_type: 4
source_version: ''
start_time: 1772835409117
status: 3
tags: []
user_id: iamsh
