artifact_uri: file:///C:/Users/iamsh/OneDrive/Desktop/AI Project/fintel/mlflow_runs/153180820146054763/eac92e531c794d4fa2242eafa8fec171/artifacts
end_time: 1772835401741
entry_point_name: ''
experiment_id: '153180820146054763'
lifecycle_stage: active
run_id: eac92e531c794d4fa2242eafa8fec171
run_name: gfc_recovery_qe1_qe2
source_name: ''
source_type: 4
source_version: ''
start_time: 1772835399124
status: 3
tags: []
user_id: iamsh
